image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - publish

cache:
  untracked: true
  policy: pull

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

build and test:
  stage: build
  services:
    - name: mcr.microsoft.com/azure-storage/azurite:latest
      alias: azurite
      command: ["azurite", "--blobHost", "0.0.0.0"]
  artifacts:
    paths:
      - TestResults/
  coverage: '/^\|\s+Total\s+\|\s+\d+\.?\d+%\s+\|\s+(\d+\.?\d+)%\s+\|\s+\d+\.?\d+%\s+\|$/'
  before_script:
    - ". build/prepare.sh"
  script:
    - "dotnet build -c $FLAVOR $BUILD_ARGS"
    - "dotnet test  -c $FLAVOR $TEST_ARGS"

publish nuget packages:
  stage: publish
  rules:
    - when: manual
  script:
    - "printenv"
    - "dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY"
